### ISSUE TITLE
Connection to Chorus

### ISSUE THREAD

**Issue by xudaondo** [anunique/ChorusGUI#2]
Hi, 
I have connected the Arduino to my FTDI in COM20, in the debug mode TAB it appears some messages (See screenshot), but I don't know if it is connected correctly, because nothing happens when the Chorus detects a new lap through the Android APP 

I have started a Race, but nothing happens when the chorus beep with each lap.

Do I have connected correctly? Or do I have to remove the Bluetooth adapter, and conect the FTDI in that port to the USB?
![debug](https://user-images.githubusercontent.com/25665942/29940649-2b4c3406-8e90-11e7-98f4-28992666bca5.png)

**Comment by xudaondo** [comment]
Maybe I need to connect the PC to Chorus with Bluetooth?

**Comment by anunique** [comment]
either you selected a wrong baudrate, wrong com port or simply didnt connect rx to tx and tx to rx.

im using a programmer all the time but bluetooth works fine too.

**Comment by xudaondo** [comment]
Which is the baudrate? 115200?
Which is the conexion?
1. FTDI to arduino pins
2. FTDI to Chorus BT pins (HC-06)
3. FTDI to Chorus pins TX and RX in the left
4. PC directly connected by BT (HC-06)

**Comment by xudaondo** [comment]
Can yo help me with this issue?
